name: sa_launcher
description: "A Game Launcher, support auto backup and cloud sync."
publish_to: 'none'
version: 1.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  # 文件选择器
  file_picker: ^10.3.3
  
  # 路径处理
  path: ^1.8.3
  
  # 剪切板处理
  super_clipboard: ^0.9.1
  
  # 路径获取
  path_provider: ^2.1.1
  
  # 状态管理
  flutter_riverpod: ^3.0.0

  # 窗口管理
  window_manager: ^0.5.0

  # 国际化和日期格式化
  intl: ^0.20.0

  # Windows ETW 进程监控
  event_tracing_windows: ^0.0.1

  # 打开链接
  url_launcher: ^6.3.2

  # 日志
  logging: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true